#debug: true

logging:
    level:
        "[de.workshops]": debug
        "[org.hibernate.SQL]": debug
        "[org.hibernate.type]": trace
        "[org.springframework.boot.web]": debug

bookdemo:
    int-param: 42
    param2: Test
    mail:
        host: mailHost
        port: 987

spring:
  datasource:
    url: jdbc:h2:./bookdemoDB;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: user
    password: pass
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    defer-datasource-initialization: true
    #open-in-view: true
  h2:
    console:
      enabled: true
      path: /h2-console


---
spring:
    config:
        activate:
            on-profile:
                - prod2

server:
  port: 8090

springdoc:
    api-docs:
        enabled: false