#debug: true

logging:
    level:
        "[de.workshops]": debug
        "[org.springframework.boot.web]": debug

bookdemo:
    int-param: 42
    param2: Test
    mail:
        host: mailHost
        port: 987

---
spring:
    config:
        activate:
            on-profile:
                - prod2

server:
  port: 8090

springdoc:
    api-docs:
        enabled: false