#debug: true

logging:
    level:
        "[de.workshops]": debug
        #"[org.hibernate.SQL]": debug
        #"[org.hibernate.type]": trace
        #"[org.springframework.boot.web]": debug
        #"[org.springframework.security]": debug

bookdemo:
    int-param: 42
    param2: Test
    mail:
        host: mailHost
        port: 987

spring:
  datasource:
    url: jdbc:h2:./bookdemoDB;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: user
    password: pass
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    defer-datasource-initialization: true
    #open-in-view: true
  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    user:
        name: dominik
        password: pass
    oauth2:
        client:
            registration:
                google:
                # client mit redirect-uri *:8080 und *:8081
                    client-id: 148971885543-co9dv22tjamh7amdonnqod69dsd721rp.apps.googleusercontent.com
                    client-secret: mXAtT6Ze7M7mK_KCb5VEyJSY   

management:
    endpoints:
        web:
            exposure:
                include: "*"

---
spring:
    config:
        activate:
            on-profile:
                - prod2

server:
  port: 8090

springdoc:
    api-docs:
        enabled: false